apiVersion: v1
kind: Service
metadata:
  name:  pallagani-rtp-service
  namespace: pallagani
spec:
  type: NodePort
  selector:
    app: pallagani-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
